DROP TABLE BATHROOMS CASCADE CONSTRAINTS;

DROP TABLE CLIENTS CASCADE CONSTRAINTS;

DROP TABLE CONTRACTORS CASCADE CONSTRAINTS;

DROP TABLE KITCHENS CASCADE CONSTRAINTS;

DROP TABLE LIVING_ROOMS CASCADE CONSTRAINTS;

DROP TABLE PROJECTS CASCADE CONSTRAINTS;

DROP TABLE PROJ_CONT CASCADE CONSTRAINTS;

-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-05-12 16:00:42 EDT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g
-- Create clients table
CREATE TABLE clients (
    client_id INTEGER NOT NULL,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(60),
    phone VARCHAR2(20),
    address VARCHAR2(200)
);

ALTER TABLE
    clients
ADD
    CONSTRAINT clients_pk PRIMARY KEY (client_id);

-- Create contractors table
CREATE TABLE contractors (
    contractor_id INTEGER NOT NULL,
    name VARCHAR2(100) NOT NULL,
    specialization VARCHAR2(50),
    phone VARCHAR2(20),
    rating NUMBER CHECK (
        rating >= 0
        AND rating <= 5
    )
);

ALTER TABLE
    contractors
ADD
    CONSTRAINT contractors_pk PRIMARY KEY (contractor_id);

-- Create projects table (Supertype)
CREATE TABLE projects (
    project_id INTEGER NOT NULL,
    project_name VARCHAR2(100) NOT NULL,
    start_date DATE,
    end_date DATE,
    budget NUMBER,
    status VARCHAR2(20) CHECK (
        status IN ('Planned', 'In Progress', 'Completed')
    ),
    client_id INTEGER NOT NULL
);

ALTER TABLE
    projects
ADD
    CONSTRAINT projects_pk PRIMARY KEY (project_id);

ALTER TABLE
    projects
ADD
    CONSTRAINT projects_clients_fk FOREIGN KEY (client_id) REFERENCES clients (client_id);

-- Create kitchens table (Subtype)
CREATE TABLE kitchens (
    project_id INTEGER NOT NULL,
    style VARCHAR2(50),
    appliance_type VARCHAR2(50),
    square_footage NUMBER
);

ALTER TABLE
    kitchens
ADD
    CONSTRAINT kitchens_pk PRIMARY KEY (project_id);

ALTER TABLE
    kitchens
ADD
    CONSTRAINT kitchens_projects_fk FOREIGN KEY (project_id) REFERENCES projects (project_id);

-- Create bathrooms table (Subtype)
CREATE TABLE bathrooms (
    project_id INTEGER NOT NULL,
    tile_type VARCHAR2(50),
    fixture_type VARCHAR2(50),
    square_footage NUMBER
);

ALTER TABLE
    bathrooms
ADD
    CONSTRAINT bathrooms_pk PRIMARY KEY (project_id);

ALTER TABLE
    bathrooms
ADD
    CONSTRAINT bathrooms_projects_fk FOREIGN KEY (project_id) REFERENCES projects (project_id);

-- Create living_rooms table (Subtype)
CREATE TABLE living_rooms (
    project_id INTEGER NOT NULL,
    flooring_type VARCHAR2(50),
    wall_color VARCHAR2(50),
    square_footage NUMBER
);

ALTER TABLE
    living_rooms
ADD
    CONSTRAINT living_rooms_pk PRIMARY KEY (project_id);

ALTER TABLE
    living_rooms
ADD
    CONSTRAINT living_rooms_projects_fk FOREIGN KEY (project_id) REFERENCES projects (project_id);

-- Create proj_cont intersection table
CREATE TABLE proj_cont (
    project_id INTEGER NOT NULL,
    contractor_id INTEGER NOT NULL
);

ALTER TABLE
    proj_cont
ADD
    CONSTRAINT proj_cont_pk PRIMARY KEY (project_id, contractor_id);

ALTER TABLE
    proj_cont
ADD
    CONSTRAINT proj_cont_projects_fk FOREIGN KEY (project_id) REFERENCES projects (project_id);

ALTER TABLE
    proj_cont
ADD
    CONSTRAINT proj_cont_contractors_fk FOREIGN KEY (contractor_id) REFERENCES contractors (contractor_id);

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             1
-- ALTER TABLE                             15
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           3
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                  13
-- WARNINGS                                 0
-- clients table
INSERT INTO
    clients (client_id, name, email, phone, address)
VALUES
    (
        1,
        'John Doe',
        'john.doe@example.com',
        '555-1234',
        '123 Main St'
    );

INSERT INTO
    clients (client_id, name, email, phone, address)
VALUES
    (
        2,
        'Jane Smith',
        'jane.smith@example.com',
        '555-5678',
        '456 Elm St'
    );

INSERT INTO
    clients (client_id, name, email, phone, address)
VALUES
    (
        3,
        'Alice Brown',
        'alice.brown@example.com',
        '555-9876',
        '789 Pine St'
    );

INSERT INTO
    clients (client_id, name, email, phone, address)
VALUES
    (
        4,
        'Bob White',
        'bob.white@example.com',
        '555-6543',
        '101 Maple Ave'
    );

INSERT INTO
    clients (client_id, name, email, phone, address)
VALUES
    (
        5,
        'Carol Green',
        'carol.green@example.com',
        '555-3210',
        '202 Oak Blvd'
    );

INSERT INTO
    clients (client_id, name, email, phone, address)
VALUES
    (
        6,
        'Dan Black',
        'dan.black@example.com',
        '555-2468',
        '303 Cedar Ln'
    );

INSERT INTO
    clients (client_id, name, email, phone, address)
VALUES
    (
        7,
        'Eve Gray',
        'eve.gray@example.com',
        '555-1357',
        '404 Birch Dr'
    );

INSERT INTO
    clients (client_id, name, email, phone, address)
VALUES
    (
        8,
        'Frank Silver',
        'frank.silver@example.com',
        '555-7890',
        '505 Walnut Rd'
    );

-- contractors table
INSERT INTO
    contractors (
        contractor_id,
        name,
        specialization,
        phone,
        rating
    )
VALUES
    (
        11,
        'Mike Johnson',
        'Electrical',
        '555-9876',
        4.5
    );

INSERT INTO
    contractors (
        contractor_id,
        name,
        specialization,
        phone,
        rating
    )
VALUES
    (12, 'Emily Davis', 'Plumbing', '555-4321', 4.8);

INSERT INTO
    contractors (
        contractor_id,
        name,
        specialization,
        phone,
        rating
    )
VALUES
    (
        13,
        'Steve Adams',
        'Landscaping',
        '555-6789',
        4.2
    );

INSERT INTO
    contractors (
        contractor_id,
        name,
        specialization,
        phone,
        rating
    )
VALUES
    (
        14,
        'Laura Bell',
        'Interior Design',
        '555-3456',
        4.7
    );

INSERT INTO
    contractors (
        contractor_id,
        name,
        specialization,
        phone,
        rating
    )
VALUES
    (15, 'Tom Carter', 'Painting', '555-9012', 4.3);

INSERT INTO
    contractors (
        contractor_id,
        name,
        specialization,
        phone,
        rating
    )
VALUES
    (16, 'Nancy Foster', 'Roofing', '555-1111', 4.6);

-- projects table
INSERT INTO
    projects (
        project_id,
        project_name,
        start_date,
        end_date,
        budget,
        status,
        client_id
    )
VALUES
    (
        1,
        'Kitchen Remodel',
        '2024-01-01',
        '2024-02-01',
        15000.00,
        'Planned',
        1
    );

INSERT INTO
    projects (
        project_id,
        project_name,
        start_date,
        end_date,
        budget,
        status,
        client_id
    )
VALUES
    (
        2,
        'Bathroom Renovation',
        '2024-03-01',
        '2024-03-15',
        8000.00,
        'In Progress',
        2
    );

INSERT INTO
    projects (
        project_id,
        project_name,
        start_date,
        end_date,
        budget,
        status,
        client_id
    )
VALUES
    (
        3,
        'Living Room Update',
        '2024-02-10',
        '2024-02-20',
        5000.00,
        'Planned',
        3
    );

INSERT INTO
    projects (
        project_id,
        project_name,
        start_date,
        end_date,
        budget,
        status,
        client_id
    )
VALUES
    (
        4,
        'Second Bathroom Renovation',
        '2024-05-10',
        '2024-05-25',
        8500.00,
        'In Progress',
        5
    );

INSERT INTO
    projects (
        project_id,
        project_name,
        start_date,
        end_date,
        budget,
        status,
        client_id
    )
VALUES
    (
        5,
        'Large Kitchen Remodel',
        '2024-06-01',
        '2024-07-15',
        25000.00,
        'Planned',
        6
    );

INSERT INTO
    projects (
        project_id,
        project_name,
        start_date,
        end_date,
        budget,
        status,
        client_id
    )
VALUES
    (
        6,
        'Master Bathroom Renovation',
        '2024-07-20',
        '2024-08-10',
        10000.00,
        'Planned',
        7
    );

INSERT INTO
    projects (
        project_id,
        project_name,
        start_date,
        end_date,
        budget,
        status,
        client_id
    )
VALUES
    (
        7,
        'Modern Living Room',
        '2024-09-01',
        '2024-09-20',
        6000.00,
        'Planned',
        1
    );

-- subtype tables
INSERT INTO
    kitchens (
        project_id,
        style,
        appliance_type,
        square_footage
    )
VALUES
    (1, 'Modern', 'Stainless Steel', 200);

INSERT INTO
    kitchens (
        project_id,
        style,
        appliance_type,
        square_footage
    )
VALUES
    (5, 'Contemporary', 'Smart Appliances', 350);

INSERT INTO
    bathrooms (
        project_id,
        tile_type,
        fixture_type,
        square_footage
    )
VALUES
    (2, 'Ceramic', 'Contemporary', 100);

INSERT INTO
    bathrooms (
        project_id,
        tile_type,
        fixture_type,
        square_footage
    )
VALUES
    (4, 'Porcelain', 'Luxury', 120);

INSERT INTO
    bathrooms (
        project_id,
        tile_type,
        fixture_type,
        square_footage
    )
VALUES
    (6, 'Stone', 'Modern', 150);

INSERT INTO
    living_rooms (
        project_id,
        flooring_type,
        wall_color,
        square_footage
    )
VALUES
    (3, 'Hardwood', 'Beige', 250);

INSERT INTO
    living_rooms (
        project_id,
        flooring_type,
        wall_color,
        square_footage
    )
VALUES
    (7, 'Laminate', 'Gray', 300);

-- project_contractor table
INSERT INTO
    proj_cont (project_id, contractor_id)
VALUES
    (1, 11);

INSERT INTO
    proj_cont (project_id, contractor_id)
VALUES
    (2, 12);

INSERT INTO
    proj_cont (project_id, contractor_id)
VALUES
    (3, 13);

INSERT INTO
    proj_cont (project_id, contractor_id)
VALUES
    (4, 14);

INSERT INTO
    proj_cont (project_id, contractor_id)
VALUES
    (5, 15);

INSERT INTO
    proj_cont (project_id, contractor_id)
VALUES
    (6, 16);