services:
  mongodb:
    image: mongo:7
    container_name: assignment3-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass123
    volumes:
      - assignment3-mongo-data:/data/db

volumes:
  assignment3-mongo-data:
