CREATE TABLE RP_INVENTORY (
    WAREHOUSE_ID NUMBER,
    PRODUCT_CODE VARCHAR2(10),
    QOH NUMBER
);

CREATE TABLE RP_WAREHOUSE (
    WAREHOUSE_ID NUMBER,
    WHSE_CITY VARCHAR2(10)
);

CREATE TABLE RP_CUSTOMERS (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR2(100),
    STREET VARCHAR2(100),
    CUST_CITY VARCHAR2(50),
    CUST_STATE VARCHAR2(50),
    ZIP VARCHAR2(10),
    BALANCE NUMBER,
    CREDIT_LIMIT NUMBER,
    REP_ID NUMBER
);

CREATE TABLE RP_SALES (
    SALES_ID NUMBER,
    LAST_NAME VARCHAR2(100),
    FIRST_NAME VARCHAR2(100),
    STREET VARCHAR2(100),
    REP_CITY VARCHAR2(50),
    REP_STATE VARCHAR2(50),
    ZIP VARCHAR2(10),
    COMMISION NUMBER,
    RATE NUMBER
);

CREATE TABLE RP_ORDER_LINES (
    ORDER_ID NUMBER,
    PRODUCT_CODE VARCHAR2(10),
    QTY_ORDERED NUMBER,
    PRICE_PAID NUMBER
);

CREATE TABLE RP_ORDERS (
    ORDER_ID NUMBER,
    ORDER_DATE DATE,
    CUSTOMER_ID NUMBER
);

CREATE TABLE RP_PRODUCTS (
    PRODUCT_CODE VARCHAR2(10),
    PRODUCT_DESCRIPTION VARCHAR2(100),
    PRODUCT_CATEGORY VARCHAR2(50),
    COST_PRICE NUMBER
);

INSERT INTO
    RP_REPS ()