DROP TABLE RP_INVENTORY;

DROP TABLE RP_WAREHOUSE;

DROP TABLE RP_CUSTOMERS;

DROP TABLE RP_REPS;

DROP TABLE RP_ORDER_LINES;

DROP TABLE RP_ORDERS;

DROP TABLE RP_PRODUCTS;

CREATE TABLE RP_INVENTORY (
    WAREHOUSE_ID NUMBER,
    PRODUCT_CODE VARCHAR2(10),
    QOH NUMBER
);

CREATE TABLE RP_WAREHOUSE (
    WAREHOUSE_ID NUMBER,
    WHSE_CITY VARCHAR2(10)
);

CREATE TABLE RP_CUSTOMERS (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR2(100),
    STREET VARCHAR2(100),
    CUST_CITY VARCHAR2(50),
    CUST_STATE VARCHAR2(50),
    ZIP VARCHAR2(10),
    BALANCE NUMBER,
    CREDIT_LIMIT NUMBER,
    REP_ID NUMBER
);

CREATE TABLE RP_REPS (
    REP_ID NUMBER,
    LAST_NAME VARCHAR2(100),
    FIRST_NAME VARCHAR2(100),
    STREET VARCHAR2(100),
    REP_CITY VARCHAR2(50),
    REP_STATE VARCHAR2(50),
    ZIP VARCHAR2(10),
    COMMISSION NUMBER,
    RATE NUMBER
);

CREATE TABLE RP_ORDER_LINES (
    ORDER_ID NUMBER,
    PRODUCT_CODE VARCHAR2(10),
    QTY_ORDERED NUMBER,
    PRICE_PAID NUMBER
);

CREATE TABLE RP_ORDERS (
    ORDER_ID NUMBER,
    ORDER_DATE DATE,
    CUSTOMER_ID NUMBER
);

CREATE TABLE RP_PRODUCTS (
    PRODUCT_CODE VARCHAR2(10),
    PRODUCT_DESCRIPTION VARCHAR2(100),
    PRODUCT_CATEGORY VARCHAR2(50),
    COST_PRICE NUMBER
);

INSERT INTO
    RP_REPS (
        REP_ID,
        LAST_NAME,
        FIRST_NAME,
        STREET,
        REP_CITY,
        REP_STATE,
        ZIP,
        COMMISSION,
        RATE
    )
VALUES
    (
        20,
        'Culp',
        'Betty',
        '1275 Main St',
        'Detroit',
        'MI',
        '48288',
        20542.50,
        0.05
    );

INSERT INTO
    RP_REPS (
        REP_ID,
        LAST_NAME,
        FIRST_NAME,
        STREET,
        REP_CITY,
        REP_STATE,
        ZIP,
        COMMISSION,
        RATE
    )
VALUES
    (
        35,
        'Manis',
        'Richard',
        '532 Jackson',
        'Toronto',
        'ON',
        'M5V2K1',
        '39216.00',
        '0.05'
    );

INSERT INTO
    RP_REPS (
        REP_ID,
        LAST_NAME,
        FIRST_NAME,
        STREET,
        REP_CITY,
        REP_STATE,
        ZIP,
        COMMISSION,
        RATE
    )
VALUES
    (
        65,
        'Large',
        'Tom',
        '1626 Taylor',
        'Chicago',
        'IL',
        '60099',
        '23487.00',
        '0.05'
    );

INSERT INTO
    RP_WAREHOUSE (WAREHOUSE_ID, WHSE_CITY)
VALUES
    (100, 'Chicago');

INSERT INTO
    RP_WAREHOUSE (WAREHOUSE_ID, WHSE_CITY)
VALUES
    (200, 'Detroit');

INSERT INTO
    RP_WAREHOUSE (WAREHOUSE_ID, WHSE_CITY)
VALUES
    (300, 'Toronto');

UPDATE
    RP_CUSTOMERS
SET
    BALANCE = 4285.25
WHERE
    CUSTOMER_ID = 408;

UPDATE
    RP_CUSTOMERS
SET
    BALANCE = 6221
WHERE
    CUSTOMER_ID = 842;

UPDATE
    RP_PRODUCTS
SET
    COST_PRICE = COST_PRICE + COST_PRICE * 0.085;

DELETE FROM
    RP_PRODUCTS
WHERE
    PRODUCT_DESCRIPTION = 'Cordless Drill';

UPDATE
    RP_CUSTOMERS
SET
    CREDIT_LIMIT = 14500
WHERE
    CUSTOMER_NAME = 'Brookings Direct';