
-- 1.
SELECT * FROM B_PRODUCTS;

-- 2.
SELECT PRODUCT_CODE
    , PROD_DESCRIPTION
    , CATEGORY_CODE
    , PRICE
    FROM B_PRODUCTS;

-- 3.
SELECT CUSTOMER_NAME
    , CREDIT_LIMIT
    , BALANCE
    FROM B_CUSTOMERS;

-- 4.
SELECT CUSTOMER_NAME
    , BALANCE
    , CREDIT_LIMIT
    FROM B_CUSTOMERS;

-- 5.
SELECT CUSTOMER_NAME
    FROM B_CUSTOMERS;

-- 6.
SELECT CUSTOMER_NAME
    , NEW_CREDIT_LIMIT * 1.12 AS NEW_CREDIT_LIMIT
    FROM B_CUSTOMERS;

-- 7.
SELECT CUSTOMER_NAME AS 'Customer Name'
    , CUSTOMER_CITY AS 'City'
    FROM B_CUSTOMERS;

-- 8.
SELECT CUSTOMER_NAME
    , CREDIT_LIMIT AS OLD_CREDIT_LIMIT
    , CREDIT_LIMIT * 1.12 AS NEW_CREDIT_LIMIT
    FROM B_CUSTOMERS;

-- 9.
SELECT CUSTOMER_ID AS 'Customer'
    , CUSTOMER_NAME AS 'Customer Name'
    , CREDIT_LIMIT AS 'Available Credit'
    FROM B_CUSTOMERS;

-- 10.
SELECT CUSTOMER_NAME
    , CUSTOMER_CITY || CUSTOMER_STATE || CUSTOMER_COUNTRY AS ADDRESS
    FROM B_CUSTOMERS;

-- 11.
SELECT CUSTOMER_NAME
    , CUSTOMER_CITY || ', ' || CUSTOMER_STATE || ' ' || CUSTOMER_COUNTRY AS ADDRESS
    FROM B_CUSTOMERS;

-- 12.
SELECT CUSTOMER_BALANCE
    || ' has a balance of '
    || CUSTOMER_BALANCE AS 'Customer Balance'
    FROM B_CUSTOMERS;

-- 13.
SELECT 'Customer '
    || CUSTOMER_ID
    || ' is located in '
    || CUSTOMER_CITY || ', '
    || CUSTOMER_STATE || ' '
    || CUSTOMER_COUNTRY AS 'Customer Location'
    FROM B_CUSTOMERS;

-- 14.
SELECT CUSTOMER_CITY AS CITY
    FROM B_CUSTOMERS;

-- 15.
SELECT DISTINCT CUSTOMER_CITY AS CITY
    FROM B_CUSTOMERS;